[package]
name = "linux-socket-recverr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0"
# Need PR #1515
nix = { git = "https://github.com/nix-rust/nix", rev = "b45d84260ec" }
